#!/bin/sh

set -e

CLONE_BRANCH=$SAIL_COMMIT_BRANCH

# If setting up a PR then just get master since we'll be fetching origin anyway
case "$SAIL_COMMIT_REF" in
  refs/pull/*)
    CLONE_BRANCH=master ;;
esac

{
  git clone -b "$CLONE_BRANCH" --single-branch https://x-access-token:"$SAIL_GIT_TOKEN"@github.com/"$SAIL_REPO_OWNER"/"$SAIL_REPO_NAME".git repo 2>/dev/null
} || {
  echo "Avast, we could not clone the $CLONE_BRANCH branch for GitHub repository $SAIL_REPO_OWNER/$SAIL_REPO_NAME."
  exit 1;
}

cd ./repo

{
  case "$SAIL_COMMIT_REF" in
    refs/pull/*) git fetch --force origin "$SAIL_COMMIT_BRANCH/head:refs/$SAIL_COMMIT_BRANCH" 2>/dev/null
    git checkout "$SAIL_COMMIT_BRANCH" ;;
  esac
} || {
  echo "Avast, we could not fetch the pull request $SAIL_COMMIT_BRANCH for GitHub repository $SAIL_REPO_OWNER/$SAIL_REPO_NAME."
  exit 1;
}

if [ -n "$SAIL_COMMIT_SHA" ]; then
  git checkout "$SAIL_COMMIT_SHA"
fi
